
import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    jobBoard: 'PflegeBrücke',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    name: 'Name',
    role: 'Role',
    admin: 'Admin',
    viewer: 'Viewer',
    signOut: 'Sign Out',
    passwordMismatch: 'Passwords do not match!',
    accountCreatedRedirect: 'Account created successfully! Redirecting...',
    dashboard: 'Dashboard',
    jobPosts: 'Job Posts',
    subscription: 'Subscription',
    candidateName: 'Candidate Name',
    specialization: 'Specialization',
    skills: 'Skills',
    city: 'City',
    country: 'Country',
    status: 'Status',
    available: 'Available',
    hired: 'Hired',
    hiredBy: 'Hired By',
    hiredDate: 'Hired on',
    markAsHired: 'Hired',
    inInterview: 'In an interview',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    users: 'Users',
    save: 'Save',
    cancel: 'Cancel',
    subscriptionExpired: 'You are not subscribed yet',
    subscriptionActive: 'Subscription Active',
    jobMarkedAsHired: 'Job marked as hired successfully',
    jobCreated: 'Job post created successfully',
    jobUpdated: 'Job post updated successfully',
    jobDeleted: 'Job post deleted successfully',
    adminDashboard: 'Admin Dashboard',
    createJobPost: 'Create Job Post',
    editJobPost: 'Edit Job Post',
    uploadFiles: 'Upload Files',
    filesUploaded: 'Files Uploaded',
    removeFile: 'Remove File',
    fileSelected: 'File selected: {fileName}',
    filesSelected: '{count} files selected',
    fileUploadSuccess: 'File(s) uploaded successfully',
    fileRemoved: 'File removed successfully',
    noFileUploaded: 'No file uploaded',
    openingFile: 'Opening file...',
    attachedFiles: 'Files',
    noFilesAttached: 'No files attached.',
    viewFile: 'View File {index}',
    fileAccessDenied: 'File access denied. Please check your subscription.',
    mySubscription: 'My Subscription',
    subscriptionStatus: 'Subscription Status',
    statusActive: 'Active',
    statusExpired: 'Expired',
    expiresOn: 'Expires on',
    subscribeNow: 'Subscribe Now',
    requestSubscription: 'Request Subscription',
    requestSubscriptioncah: 'Request Subscription',
    subscriptionExpiredNotice: 'You need a subscription to access this feature. Subscribe now and explore all benefits!',
    darkMode: 'Dark Mode',
    theme: 'Theme',
    contactAdminToRenew: 'Please contact the administrator to renew your access.',
    subscriptionExpiredTitle: 'You are not subscribed yet',
    stripeCheckoutLoading: 'Redirecting to Stripe checkout...',
    paymentSuccessful: 'Payment Successful!',
    subscriptionUpdated: 'Your subscription has been updated.',
    paymentCancelled: 'Payment Cancelled',
    paymentCancelledMessage: 'Your payment was cancelled. You can try again from the subscription page.',
    backToSubscription: 'Back to Subscription',
    operatedBy: 'This platform is operated by DaF Institute.',
    createdBy: 'Created by DeepSightX',
    copyright: '© 2025 DeepSightX. All rights reserved.',
    contactInfo: 'Contact Info',
    socialMedia: 'Social Media',
    address: 'Address',
    phoneNumber: 'Phone Number',
  // landingPag
  welcomeTo: 'Welcome to',
  landingDescription: 'PflegeBrücke connects German care institutions with skilled international nurses in a smooth, efficient, and ethical way.',
  getStarted: 'Get Started',
  learnMore: 'Learn More',
  aboutTitle: 'Why PflegeBrücke?',
  aboutDescription: 'We simplify recruitment, support onboarding, and ensure long-term retention for healthcare staff.',
  featureOneTitle: 'Streamlined Hiring',
  featureOneDesc: 'Fast-track your recruitment process with verified international candidates.',
  featureTwoTitle: 'Cultural Integration',
  featureTwoDesc: 'We offer support for language and culture so newcomers feel at home.',
  featureThreeTitle: 'Retention Focus',
  featureThreeDesc: 'We don’t just help you hire—we help you retain for the long term.',
  activateTitle: 'Cash Subscription Requests',
  noRequests: 'No pending requests',
  accept: 'Accept',
  reject: 'Reject',
  adminPanel: 'Admin Panel',
  adminactivateTitle:'Abo-Anfragen',
  cancelHiring: 'Cancel Hiring',
  inInterview: 'Interview',
  cancelInterview: 'Cancel Interview',
  redirectingToJobs: 'Redirecting you to the job posts...',
  failedToUpdateSubscription: 'Failed to update subscription.',
  jobStatusUpdated: 'Job status updated successfully!',
  cashRequests: 'Cash Requests',
  noRequests: 'No pending requests',
  requestedDuration: 'Requested Duration',
  months: 'months',
  approve: 'Approve',
  reject: 'Reject',
  requestSuccess: 'Cash request sent successfully.',
  requestExists: 'You already have a pending request.',
  requestRejected: 'Request has been rejected.',
  requestApproved: 'Request has been approved and subscription updated.',
  unauthorized: 'You are not authorized to perform this action.',
  serverError: 'Something went wrong. Please try again.',
  cashRequests: ' Requests',
  approve: 'Approve',
  reject: 'Reject',
  requestRejected: 'Request has been rejected',
  requestApproved: 'Request has been approved',
  serverError: 'Server error occurred',
  requestedOn: 'Requested On',
  cashRequests: ' Requests',
  noCashRequests: 'There are no requests currently.',
  name: 'Name',
  email: 'Email',
  requestedOn: 'Requested On',
  approve: 'Approve',
  reject: 'Reject',
  payCash: 'Pay Cash',
  month: 'month',
  requestSent: 'Request Sent',
  waitingForApproval: 'Waiting for admin approval',
  error: 'Error',
  users: 'Users',
  noUsers: 'No users found.',
  joinedOn: 'Joined on',
  subscriptionEnd: 'Subscription ends',
  noSubscription: 'No subscription',
  totalUsers: 'Total Users',
  activeSubscribers: 'Active Subscribers',
  noSubscription: 'No Subscription',
  requestSent: 'Request Sent',
  adminWillReview: 'An admin will review your request shortly.',
  couldNotSendRequest: 'Could not send subscription request.',
  subscribeNowTitle: 'Subscribe now and unlock all features!',
  subscribeNowSubtitle: 'Upgrade to a full experience — post jobs, access candidates, and more.',
  requestPendingTitle: 'Request already sent',
  requestPendingMessage: 'You have already requested a subscription. Please wait for admin approval.',
  requestSent: 'Request Sent',
  requestSentDescription: 'Your subscription request has been submitted successfully.',
  signIn: "Sign In",
  signOut: "Sign Out",
  signUp: "Sign Up",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  forgotPassword: "Forgot Password?",
  resetPassword: "Reset Password",
  sendResetCode: "Send Reset Code",
  verifyEmail: "Verify Your Email",
  verificationCode: "Verification Code",
  verify: "Verify",
  emailVerified: "Email verified successfully!",
  checkEmail: "Check your email",
  newPassword: "New Password"


},


  de: {
    jobBoard: 'PflegeBrücke',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    name: 'Name',
    role: 'Rolle',
    admin: 'Administrator',
    viewer: 'Betrachter',
    signOut: 'Abmelden',
    passwordMismatch: 'Die Passwörter stimmen nicht überein!',
    accountCreatedRedirect: 'Konto erfolgreich erstellt! Sie werden weitergeleitet...',
    dashboard: 'Dashboard',
    jobPosts: 'Stellenausschreibungen',
    subscription: 'Abonnement',
    candidateName: 'Kandidatenname',
    specialization: 'Spezialisierung',
    skills: 'Fähigkeiten',
    city: 'Stadt',
    country: 'Land',
    status: 'Status',
    available: 'Verfügbar',
    hired: 'Eingestellt',
    hiredBy: 'Eingestellt von',
    hiredDate: 'Eingestellt am',
    markAsHired: 'Einstellen',
    cancelHiring:'Stornieren',
    create: 'Erstellen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    subscriptionExpired: 'Sie haben noch kein Abonnement',
    subscriptionActive: 'Abonnement aktiv',
    jobMarkedAsHired: 'Stelle erfolgreich als besetzt markiert',
    jobCreated: 'Stellenausschreibung erfolgreich erstellt',
    jobUpdated: 'Stellenausschreibung erfolgreich aktualisiert',
    jobDeleted: 'Stellenausschreibung erfolgreich gelöscht',
    adminDashboard: 'Admin Dashboard',
    createJobPost: 'Stellenausschreibung erstellen',
    editJobPost: 'Stellenausschreibung bearbeiten',
    uploadFiles: 'Dateien hochladen',
    filesUploaded: 'Dateien hochgeladen',
    removeFile: 'Datei entfernen',
    fileSelected: 'Datei ausgewählt: {fileName}',
    filesSelected: '{count} Dateien ausgewählt',
    fileUploadSuccess: 'Datei(en) erfolgreich hochgeladen',
    fileRemoved: 'Datei erfolgreich entfernt',
    noFileUploaded: 'Keine Datei hochgeladen',
    openingFile: 'Datei wird geöffnet...',
    attachedFiles: 'Dateien',
    noFilesAttached: 'Keine Dateien angehängt.',
    viewFile: 'Datei {index} ansehen',
    fileAccessDenied: 'Dateizugriff verweigert. Bitte überprüfen Sie Ihr Abonnement.',
    mySubscription: 'Mein Abonnement',
    subscriptionStatus: 'Abonnementstatus',
    statusActive: 'Aktiv',
    statusExpired: 'Abgelaufen',
    expiresOn: 'Läuft ab am',
    subscribeNow: 'Jetzt abonnieren',
    requestSubscription: 'Abonnement erneuern',
    subscriptionExpiredNotice: 'Sie benötigen ein Abonnement, um diese Funktion zu nutzen. Jetzt abonnieren und alle Vorteile entdecken!',
    lightMode: 'Heller Modus',
    darkMode: 'Dunkler Modus',
    theme: 'Thema',
    contactAdminToRenew: 'Bitte kontaktieren Sie den Administrator, um Ihren Zugang zu erneuern.',
    subscriptionExpiredTitle: 'Sie haben noch kein Abonnement',
    stripeCheckoutLoading: 'Weiterleitung zum Stripe-Checkout...',
    paymentSuccessful: 'Zahlung erfolgreich!',
    subscriptionUpdated: 'Ihr Abonnement wurde aktualisiert.',
    paymentCancelled: 'Zahlung abgebrochen',
    paymentCancelledMessage: 'Ihre Zahlung wurde abgebrochen. Sie können es von der Abonnementseite erneut versuchen.',
    backToSubscription: 'Zurück zum Abonnement',
    operatedBy: 'Diese Plattform wird vom DaF-Institut betrieben.',
    createdBy: 'Erstellt von DeepSightX',
    copyright: '© 2025 DeepSightX. Alle Rechte vorbehalten.',
    contactInfo: 'Kontaktinformation',
    socialMedia: 'Soziale Medien',
    address: 'Adresse',
    phoneNumber: 'Telefonnummer',
    adminPanel: 'Admin Bereich',
    // landingPag
    
  welcomeTo: 'Willkommen bei',
  landingDescription: 'PflegeBrücke verbindet deutsche Pflegeeinrichtungen mit qualifizierten internationalen Pflegekräften – effizient und ethisch.',
  getStarted: 'Jetzt starten',
  learnMore: 'Mehr erfahren',
  aboutTitle: 'Warum PflegeBrücke?',
  aboutDescription: 'Wir vereinfachen die Rekrutierung, unterstützen bei der Eingliederung und fördern langfristige Bindung.',
  featureOneTitle: 'Effiziente Einstellung',
  featureOneDesc: 'Beschleunigen Sie Ihre Einstellung mit geprüften internationalen Kandidaten.',
  featureTwoTitle: 'Kulturelle Integration',
  featureTwoDesc: 'Sprach- und Kulturunterstützung, damit sich Pflegekräfte wohlfühlen.',
  featureThreeTitle: 'Langfristige Bindung',
  featureThreeDesc: 'Wir helfen nicht nur bei der Einstellung – sondern auch beim Halten des Personals.',
  activateTitle: 'Bargeld-Abonnementanfragen',
  noRequests: 'Keine ausstehenden Anfragen',
  accept: 'Akzeptieren',
  reject: 'Ablehnen',
  inInterview: 'Einladen',
  cancelInterview: 'Absagen',
  jobStatusUpdated: 'Status erfolgreich aktualisiert!',
  activateTitle: 'Subscription Requests',
  cashRequests: 'Bargeldanfragen',
  noRequests: 'Keine ausstehenden Anfragen',
  requestedDuration: 'Angeforderte Dauer',
  months: 'Monate',
  approve: 'Genehmigen',
  reject: 'Ablehnen',
  requestSuccess: 'Bargeldanfrage wurde erfolgreich gesendet.',
  requestExists: 'Sie haben bereits eine ausstehende Anfrage.',
  requestRejected: 'Anfrage wurde abgelehnt.',
  requestApproved: 'Anfrage wurde genehmigt und das Abo aktualisiert.',
  unauthorized: 'Sie sind nicht berechtigt, diese Aktion auszuführen.',
  serverError: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
  cashRequests: 'Anfragen',
  approve: 'Genehmigen',
  reject: 'Ablehnen',
  requestRejected: 'Anfrage wurde abgelehnt',
  requestApproved: 'Anfrage wurde genehmigt',
  serverError: 'Serverfehler ist aufgetreten',
  requestedOn: 'Angefordert am',
  cashRequests: 'Anfragen',
  users: 'Benutzer',
  noCashRequests: 'Derzeit keine Anfragen.',
  name: 'Name',
  email: 'E-Mail',
  requestedOn: 'Angefordert am',
  approve: 'Genehmigen',
  reject: 'Ablehnen',
  payCash: 'Bar bezahlen',
  month: 'Monat',
  requestSent: 'Anfrage gesendet',
  waitingForApproval: 'Warten auf Admin-Genehmigung',
  error: 'Fehler',
  users: 'Benutzer',
  noUsers: 'Keine Benutzer gefunden.',
  joinedOn: 'Beigetreten am',
  subscriptionEnd: 'Abo endet am',
  noSubscription: 'Kein Abo',
  totalUsers: 'Gesamtanzahl Benutzer',
  activeSubscribers: 'Aktive Abonnenten',
  noSubscription: 'Keine Abonnenten',
  requestSent: 'Anfrage gesendet',
  adminWillReview: 'Ein Administrator wird Ihre Anfrage bald prüfen.',
  couldNotSendRequest: 'Abonnementanfrage konnte nicht gesendet werden.',
  subscribeNowTitle: 'Abonniere jetzt und schalte alle Funktionen frei!',
  subscribeNowSubtitle: 'Upgrade für das volle Erlebnis – Jobs posten, auf Kandidaten zugreifen und mehr.',
  requestPendingTitle: 'Anfrage bereits gesendet',
  requestPendingMessage: 'Du hast bereits ein Abonnement angefragt. Bitte warte auf die Genehmigung durch den Admin.',
  requestSent: 'Anfrage gesendet',
  requestSentDescription: 'Deine Abonnementanfrage wurde erfolgreich übermittelt.',
  signIn: "Einloggen",
  signOut: "Ausloggen",
  signUp: "Registrieren",
  email: "E-Mail",
  password: "Passwort",
  confirmPassword: "Passwort bestätigen",
  forgotPassword: "Passwort vergessen?",
  resetPassword: "Passwort zurücksetzen",
  sendResetCode: "Zurücksetzungscode senden",
  verifyEmail: "Bestätigen Sie Ihre E-Mail",
  verificationCode: "Bestätigungscode",
  verify: "Bestätigen",
  emailVerified: "E-Mail erfolgreich bestätigt!",
  checkEmail: "Überprüfen Sie Ihre E-Mail",
  newPassword: "Neues Passwort"

},

};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key, options) => {
    let translation = translations[language][key] || key;
    if (options) {
      Object.keys(options).forEach(optionKey => {
        translation = translation.replace(`{${optionKey}}`, options[optionKey]);
      });
    }
    return translation;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'de' : 'en');
  };

  const value = {
    language,
    setLanguage,
    t,
    toggleLanguage
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
